name: GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install WARP
        run: |
          sudo apt update && \
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg && \
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list && \
          sudo apt update && \
          sudo apt install -y cloudflare-warp && \
          sudo warp-cli --accept-tos registration new && \
          sudo warp-cli --accept-tos mode warp+doh && \
          sudo warp-cli --accept-tos connect && \
          sleep 5

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 400 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Install, build and archive
        run: |
          bun install && \
          bun run build && \
          tar -czvf build.tar.gz -C dist .

      - name: Upload build artifacts to VPS
        run: |
          scp -i ~/.ssh/id_ed25519 build.tar.gz roki@[${{ secrets.SSH_HOST }}]:${{ secrets.TARGET_DIRECTORY }}/build.tar.gz

      - name: Deploy application on VPS
        run: |
          ssh -i ~/.ssh/id_ed25519 roki@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.TARGET_DIRECTORY }} && \
            ls | grep -v 'build.tar.gz' | xargs rm -rf && \
            tar -xzvf build.tar.gz && \
            rm -rf build.tar.gz && \
            pm2 restart rokimiftah.me
            pm2 reset all
            rm -rf ~/.cache
            rm -rf ~/.local/share/zsh/chpwd-recent-dirs
            rm -rf ~/.zsh_history
            rm -rf ~/.z
          "
